### ISSUE TITLE
Add statistics block to front page

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#126]
Add a statistics block containing number of APIs, users and organizations to front page.

Enhancement idea for later: nr of relayed API calls.

# Definition of done
* [ ] Any user can see statistics about APIKA on the front page
  * [ ] number of added public APIs
  * [ ] number of signed up users
  * [ ] number of added organizations.
* [ ] The style of the block is inline with the style of the front page.

# Wireframe

1. Right now after the site name and search field in front page, the next section appearing shows latest APIs.
The new statistics block can come before that section.

![statisticsblock](https://cloud.githubusercontent.com/assets/17976243/22062394/20347840-dd82-11e6-8817-7e4bb3c321f8.png)

Statistical information can be shown as cards.
![apistatistics](https://cloud.githubusercontent.com/assets/17976243/22062277/9e1b3614-dd81-11e6-8a0a-b78c5388b14a.png)
![organinzationstatistics](https://cloud.githubusercontent.com/assets/17976243/22062291/ad2a03f6-dd81-11e6-8d37-838d623f3b09.png)
![usersstatistics](https://cloud.githubusercontent.com/assets/17976243/22062301/ba52c612-dd81-11e6-8bb4-e50f731c89a3.png)

 (e.g. https://almsaeedstudio.com/themes/AdminLTE/index2.html)

the primary suggestions is to keep the cards with minimal.neutral colors.

**Comment by Nazarah** [comment]
@bajiat added a low fidelity wireframe to give you an idea about how the statistical information can appear in the landing page. Please have a review and let me know about your feedback and improvement suggestions. If you finalize the design, I'd make high fidelity wireframe.

**Comment by bajiat** [comment]
@Nazarah 
I like the position of the statistics block, but I'm wondering whether it will take up too much space? Could you experiment having the block on the right side of the Latest APIs?

Icons are good. For titles, I would make some changes
- "Added public APIs" >"Public APIs" (or could it be even just "APIs")
- "Added organizations" "Organizations"

**Comment by Nazarah** [comment]
@bajiat Here are two screenshots of the view after you suggested the modifications
![landingpagenew_2](https://cloud.githubusercontent.com/assets/17976243/22011207/816dc946-dc96-11e6-93f7-07d9faa45771.png)
![landingpagenew_3](https://cloud.githubusercontent.com/assets/17976243/22011209/817525c4-dc96-11e6-916d-ca01ca6fa8a4.png)
Now the at a glance section comes at the same level as recent APIs
1st view shows when 2 cards are side by side and another card is at bottom
2nd view shows 3 cards as a stack
There are a few things to consider about the modified view
1. The number of recent API cards becomes smaller (now 4)
2. If we consider the 2nd view, there is not an even distribution of space between 2 sections. At a glance section remains with a lot of white space, while the Recent APIs look congested.
The 1st view remedies this problem. However, since there is only 3 cards at the moment, so there is still some white space left in the At  A Glance section.

**Comment by bajiat** [comment]
@Nazarah Your original design with the statistics block before the latest APIs was better than my idea with the block on the side. It takes too much space and also looks confusing.

Thanks for experimenting, though!

**Comment by bajiat** [comment]
@Nazarah Can you provide a hi-fidelity wireframe for @snittoor ? Thanks!

**Comment by Nazarah** [comment]
Uploaded the hi fidelity prototypes

to @snittoor 
I didn't have access to the PSD file for the font awesome icon which is originally used to indicate organizations (icon name: address-card). So in the organization statistics card, that specific icon should be used.
The style of statistics cards is from: https://almsaeedstudio.com/themes/AdminLTE/index2.html

Please let me know if you are able to access the code for using the styling of the cards. Otherwise, we can use the basic APINF card style to modify the statistics card design.
