### ISSUE TITLE
Organisation view to APIs

### ISSUE THREAD

**Issue by kyyberi** [Digipalvelutehdas/APIKA#4]
As a API owner I want to see all APIs from my organisation in a visually attractive format. This page is part of our PR.

**Comment by Nazarah** [comment]
@kyyberi is there any possibility that 2 organizations can jointly work on developing on API? or this case is very rare?

**Comment by Nazarah** [comment]
@kyyberi if we keep a settings tab in an organization's profile, what things would you expect there to include?
For example: Making an organization public/private, deleting an organization, associating APIs with organization, etc.? what do you think about these options.
Also apart from the contact personnel for an organization, what about other people under the organization?

**Comment by Nazarah** [comment]
Here are some ideas about the organization catalog.

1. Organization catalog can be accessed from the topbar catalof menu
![landingpagea](https://cloud.githubusercontent.com/assets/17976243/20381625/e2bb19da-acb0-11e6-8bbe-a55120e126e6.png)

2. You can see the organizations in both card and table view.
The card will show Organization name, Description, and no. of API and Bookmarks.
You can click the bookmark icon to save it in your organization lists
![organizationcatalog](https://cloud.githubusercontent.com/assets/17976243/20381899/343087d6-acb2-11e6-92fe-52fc3455049c.png)

3. On clicking a card, you will be able to see overview information of an organization in a modal window.
There would be additional information about no. of people in the organization and average rating as icons
In addition, it would show you the top most popular APIs in your organization
there would be a link to go to the organization profile.
![organizationcatalog2](https://cloud.githubusercontent.com/assets/17976243/20381951/7702e64e-acb2-11e6-91a9-9e7838c24fa0.png)

4. Organization list can be filtered based on API life cycle and API tags
![organizationcatalog3](https://cloud.githubusercontent.com/assets/17976243/20382030/c3762cf2-acb2-11e6-89fb-49366f7a4aeb.png)

**Comment by Nazarah** [comment]
@kyyberi since APIKA doesn't yet have any organization profile view, i sketched some design ideas of how it may look. Please give your feedback about this:

1. The Organization profile can have similar look like that of am API profile. 
Top part of profile can contain name, logo, owner information, creation date, bookmark and star rating option.
Details page can contain description, contact details and list of APIs belonging to the organization.
Clicking on the API name would redirect the user to the API profile
![organizationprofile1](https://cloud.githubusercontent.com/assets/17976243/20422971/3e22f6a6-ad76-11e6-81c4-f028bde65901.png)

2. People tab can include information about persons under an organization, their designation and contact details.
Organization owner/APIKA admin would be able to add and modify this information.
![organizationprofile2](https://cloud.githubusercontent.com/assets/17976243/20423065/d7684622-ad76-11e6-9f43-4a959b67111d.png)

3. I need to know what type settings control should be included in this settings tab for an organization.
right now I can think about managing visibility, adding APIs and deleting and organization.
Please give me about your list of features that might be included here.
![organizationprofile3](https://cloud.githubusercontent.com/assets/17976243/20423096/0ae82152-ad77-11e6-9b89-e7e7be3375c5.png)

**Comment by Nazarah** [comment]
@kyyberi If we add an organization, should there be option to make it public/private?
For example, in the Add form, the default value can be public.
I was thinking about how an organization profile should look if it is private/public, should we include a toggler to control its visibility.

**Comment by kyyberi** [comment]
Organization list is by default public. As MVP it contains just basic information and contact. API list is extended (or reduced) when ever API is published (set visibility to public). If I'm from the given organisation I should see all APIs regardless of visibility. The visibility of API for public should be indicated somehow.

**Comment by kyyberi** [comment]
I kind of dislike the idea on clicking or pointing to menu to find organisations etc. That may remain, but seek for options to select organisations other way. Could there be something below the search field?
