### ISSUE TITLE
wireframe for "Showing organization APIs on organization page"

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#80]
#74

**Comment by Nazarah** [comment]
Added wireframes to issue #74

**Comment by bajiat** [comment]
I would suggest not to have infinite scrolling on organization page, but rather have paging just like in the original API catalog.

**Comment by bajiat** [comment]
If the API is public instead of private, where is the lifecycle phase tag shown? I assume that most organization APIs will actually be public. Connecting them to the organization just makes it easier e.g. for developers to find all APIs published by a certain organization.

**Comment by bajiat** [comment]
Depricated should be Deprecated

**Comment by bajiat** [comment]
And I would suggest to use the lifecycle stages: design, development, testing, production, deprecated

**Comment by bajiat** [comment]
LIfecycle tag colors are ok

**Comment by Nazarah** [comment]
"If the API is public instead of private, where is the lifecycle phase tag shown? I assume that most organization APIs will actually be public. Connecting them to the organization just makes it easier e.g. for developers to find all APIs published by a certain organization."

If an API owner suggests one of his/her private APIs then, when the request is approved, should we make the API public by default?

**Comment by Nazarah** [comment]
@bajiat 
"I would suggest not to have infinite scrolling on organization page, but rather have paging just like in the original API catalog."

If we wish to implement the organization profile page functioning the way APInf project page does, I'd suggest to have an infinite scrolling there. Right now with APInf project page, you can always browse between sections either by clicking on them or scrolling up/down. 
I'm not sure with that styling how good the pagination would work.
But then again, if we decide to go with the current tabbing style, pagination can be added.

**Comment by bajiat** [comment]
@Nazarah 

I don't think we have the right to set a private API to public. That is something that should be explicitly changed by API owner. But when an API is connected to an organization, should we somehow make clear that the organization managers will inherit the rights to manage the API?

Infinite scrolling can be quite unusable on a page that contains a catalog, especially if we have an organization that has a lot of APIs. This would only work if we would have an organization page and only a subset of APIs would be shown on the organization page (latest or most popular). If the user wanted to see more, they would be redirected to API catalog with the filter organization. 

But if all organization APIs are on the organization page (which I believe was the original request for APIKA), there should be possibility for pagination because of catalog.

**Comment by Nazarah** [comment]
@bajiat thanks for clarifying the queries. I can incorporate a notification text informing the API owner that organization manager would inherit managerial role for private APIs as well.
I think Pagination would be possible to implement. I'll sketch somehting and show u. :)

**Comment by Nazarah** [comment]
@bajiat added the necessary changes and uploaded the wireframes to the main issue.

**Comment by bajiat** [comment]
@Nazarah I think 'deprecated' should be red. Users should be warned not to use deprecated APIs. 'unknown' can be grey.

**Comment by Nazarah** [comment]
@bajiat added the wireframes with above mentioned changes in the original issue.
Please have a review.

**Comment by bajiat** [comment]
@Nazarah Changes are OK.
